CREATE TABLE clientes(
	cpf VARCHAR(11) NOT NULL PRIMARY KEY,
	idendereco INT NOT NULL, 
	nome VARCHAR(30) NOT NULL,
	email VARCHAR(50) NOT NULL,
	telefone_celular VARCHAR(14) NOT NULL,
	telefone_fixo VARCHAR(8),
	CONSTRAINT fk_id_idendereco FOREIGN KEY (idendereco) REFERENCES endereco (idendereco) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE endereco(
	idendereco INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	rua VARCHAR(30) NOT NULL,
	bairro VARCHAR(20) NOT NULL,
	cep VARCHAR(8) NOT NULL,
	complemento VARCHAR(20)
);


CREATE TABLE servico(
	idservico INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	nomeservico VARCHAR(40) NOT NULL UNIQUE,
	preco NUMERIC(10,2) CHECK(preco > 0) NOT NULL
);


CREATE TABLE peca(
	idpeca INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	tipopeca VARCHAR(40) NOT NULL,
	nomepeca VARCHAR(40) NOT NULL UNIQUE,
	preco NUMERIC(10,2) CHECK(preco > 0) NOT NULL
);

CREATE TABLE pedido(
	idpedido INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	cpf VARCHAR NOT NULL,
	idservico INTEGER NOT NULL,
	idpeca INTEGER NOT NULL,
	total NUMERIC(10,2) CHECK(total > 0) NOT NULL,
	CONSTRAINT fk_id_cpf FOREIGN KEY (cpf) REFERENCES clientes (cpf) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_id_servico FOREIGN KEY (idservico) REFERENCES servico (idservico) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_id_peca FOREIGN KEY (idpeca) REFERENCES peca (idpeca) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE pecapedido (
    idpeca INTEGER NOT NULL,
    idpedido INTEGER NOT NULL,
    CONSTRAINT pk_id_peca_pedido PRIMARY KEY (idpeca, idpedido),
    CONSTRAINT fk_id_peca FOREIGN KEY (idpeca) REFERENCES peca (idpeca) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_id_pedido FOREIGN KEY (idpedido) REFERENCES pedido (idpedido) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE servicopedido(
	idservico INTEGER NOT NULL,
	idpedido INTEGER NOT NULL,
	CONSTRAINT pk_id_servico_pedido PRIMARY KEY (idservico, idpedido),
    CONSTRAINT fk_id_servico FOREIGN KEY (idservico) REFERENCES servico (idservico) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_id_pedido FOREIGN KEY (idpedido) REFERENCES pedido (idpedido) ON DELETE CASCADE ON UPDATE CASCADE
);



